[tool.poetry]
name = "ai-test2"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
latent-diffusion = {git = "https://github.com/CompVis/latent-diffusion.git", rev = "main"}
omegaconf = "^2.1.1"
Pillow = "^9.1.0"
einops = "^0.4.1"
pytorch-lightning = "^1.6.0"
#torchvision = {url = "https://download.pytorch.org/whl/cu115/torchvision-0.12.0%2Bcu115-cp310-cp310-linux_x86_64.whl"}
#torch= {url = "https://download.pytorch.org/whl/cu115/torch-1.11.0%2Bcu115-cp310-cp310-linux_x86_64.whl"}
taming-transformers = {git = "https://github.com/CompVis/taming-transformers.git"}
transformers = "^4.18.0"
Flask = "^2.1.1"
webargs = "^8.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
